#!/bin/bash
if [[ $(id -u) -eq 0 ]];then 
    apt install -y apache2 phpmyadmin mariadb-server php8.4
    cp -r ../../pageWeb/arianeLaunchMonitor/* /var/www/html/
else 
    echo "Réessayez en tant qu'administrateur";
fi
